name: CI

on:
  push:
    branches:
    - main
    - feature/*
    - bugfix/*
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['16', '17', '18']
    steps:
    - uses: actions/checkout@v3
      
    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node }}

    - name: [vite] Install dependencies
      run: npm install
      working-directory: ./packages/vite
    - name: [vite] Build assembly
      run: npm run build
      working-directory: ./packages/vite

    - name: [renderer] Install dependencies
      run: npm install
      working-directory: ./packages/renderer
    - name: [renderer] Build assembly
      run: npm run build
      working-directory: ./packages/renderer

